# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc4832a9c6f414cdd7a770f640b1b20709f7ab8faeb4165f6b2372fc64af6d8cc6a8f32c2f28e780863845e8cda7bdebbd6202bff5b8ffefb4c7cbbc264ed630

test:
  secret_key_base: dd31c9cd5ada94ad35f2744cc6ea57f43c07976b0fbe2c588a6120da4b412156cba01e82cbe6c6343a8b175e7aeb8c82d3d6794b641d0a7131064fff5d30bc91

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
